Repository DDD-Community/jsonWeb-front, pull requests merged in 2022-12, with the labels that each got.

#22 PR 빌드테스트 자동화 및 NotFound 제작
  .github/workflows/ci.yml
  src/App.tsx
  src/pages/NotFound.tsx
  src/pages/cafeList/cafeItem.tsx
  src/pages/cafeList/cafeList.tsx
  src/pages/cafeList/index.tsx
  src/pages/detail/detail.tsx
  src/pages/detail/index.tsx
  src/pages/login/index.tsx
  src/pages/login/login.tsx
  src/pages/myAccount/index.tsx
  src/pages/myAccount/myAccount.tsx
Labels: setting, v1.0, 우선순위 높음

#29 #24 feat(main): 메인페이지 UI 구현
  .eslintrc.json
  public/index.html
  public/manifest.json
  src/App.css
  src/App.tsx
  src/assets/carouselImg.png
  src/assets/svg/EXITLogo.svg
  src/assets/svg/downArrow.svg
  src/assets/svg/heart_gray.svg
  src/assets/svg/heart_purple.svg
  src/assets/svg/icon.tsx
  src/assets/svg/leftArrow.svg
  src/assets/svg/nav_gray.svg
  src/assets/svg/nav_purple.svg
  src/assets/svg/rightArrow.svg
  src/assets/svg/search.svg
  src/assets/svg/star.svg
  src/assets/svg/upArrow.svg
  src/components/blocks/Card/Card.tsx
  src/components/blocks/Card/CardList.tsx
  src/components/blocks/Card/style.ts
  src/components/blocks/Carousel/index.tsx
  src/components/blocks/Carousel/style.ts
  src/components/blocks/Header/index.tsx
  src/components/blocks/Header/style.ts
  src/components/blocks/Menu/index.tsx
  src/components/blocks/Menu/style.ts
  src/components/blocks/Nav/index.tsx
  src/components/blocks/Nav/style.ts
  src/components/blocks/block.tsx
  src/components/template/layoutWrapper.tsx
  src/components/template/pages.tsx
  src/lib/data/genreData.ts
  src/lib/data/navData.ts
  src/pages/cafeList/cafeItem.tsx
  src/pages/cafeList/index.tsx
  src/pages/cafeList/style.ts
  src/styles/Global.tsx
  src/types/.gitkeep
  src/types/types.ts
Labels: enhancement, v1.0, feature, 우선순위 높음

#34 setting : store, query, E2E test, path alias 기능 스켈레톤 세팅
  .eslintrc.json
  .github/workflows/ci.yml
  craco.config.js
  cypress.config.ts
  cypress/e2e/1-getting-started/todo.cy.js
  cypress/e2e/2-typicode-test/typicode.cy.js
  cypress/fixtures/example.json
  cypress/fixtures/typicode/index.json
  cypress/plugins/index.js
  package-lock.json
  package.json
  src/App.tsx
  src/api/client.ts
  src/api/queryClient.ts
  src/lib/hooks/hook.ts
  src/lib/hooks/queries/cafe/.gitkeep
  src/lib/hooks/queries/member/.gitkeep
  src/lib/hooks/queries/typicode/index.ts
  src/lib/hooks/queries/typicode/useGetTypiCodeById.ts
  src/pages/typiCode/index.tsx
  src/store/Cafe/.gitkeep
  src/store/Member/.gitkeep
  src/store/Typicode/TypicodeState.ts
  src/store/Typicode/index.ts
  src/types/cafe/.gitkeep
  src/types/typicode/typicode.d.ts
  tsconfig.json
  tsconfig.paths.json
  yarn.lock
Labels: enhancement, setting, v1.0, 우선순위 높음

#35 [feat/login] Fix: Social login & logout page
  README.md
  public/index.html
  src/App.tsx
  src/assets/svg/icon.tsx
  src/assets/svg/loginLogo.svg
  src/components/blocks/modal/modal.tsx
  src/components/blocks/modal/modalStyle.tsx
  src/components/blocks/modal/portal.tsx
  src/lib/hooks/useLogin.ts
  src/pages/detail/index.tsx
  src/pages/login/index.tsx
  src/pages/login/kakaoSign.tsx
  src/pages/login/loginModal.tsx
  src/pages/login/loginStyle.tsx
  src/styles/Theme/theme.ts
  yarn.lock
Labels: v1.0, feature, 우선순위 높음, fix

#38 feat/reviewEdit : 리뷰 작성페이지 구현
  cypress/e2e/3-review/edit.cy.js
  cypress/fixtures/review/index.json
  src/App.tsx
  src/assets/svg/arrow_down.svg
  src/assets/svg/icon.tsx
  src/assets/svg/lockRate.svg
  src/assets/svg/starRate.svg
  src/components/blocks/Chips/index.style.tsx
  src/components/blocks/Chips/index.tsx
  src/components/blocks/Header/style.ts
  src/components/blocks/SelectBox/index.style.tsx
  src/components/blocks/SelectBox/index.tsx
  src/components/blocks/Star/index.style.tsx
  src/components/blocks/Star/index.tsx
  src/components/blocks/TextArea/index.style.tsx
  src/components/blocks/TextArea/index.tsx
  src/components/template/AppLayoutWrapper.tsx
  src/constants/.gitkeep
  src/constants/aria-label/index.ts
  src/constants/index.ts
  src/lib/data/evaluationData.ts
  src/lib/hooks/useSelect/index.tsx
  src/pages/login/index.tsx
  src/pages/review/edit/index.style.tsx
  src/pages/review/edit/index.tsx
  src/styles/Global.tsx
  src/styles/Theme/theme.ts
  src/types/review/index.d.ts
  src/types/types.ts
  yarn.lock
Labels: enhancement, v1.0, feature, 우선순위 높음

#40 feat/mypage: 마이페이지 UI 구현
  src/App.tsx
  src/lib/data/mypageData.ts
  src/lib/data/navData.ts
  src/pages/NotFound.tsx
  src/pages/cafeList/style.ts
  src/pages/login/index.tsx
  src/pages/login/kakaoSign.tsx
  src/pages/login/loginStyle.tsx
  src/pages/login/style.tsx
  src/pages/myAccount/index.tsx
  src/pages/myAccount/like.tsx
  src/pages/myAccount/style.tsx
  src/styles/Global.tsx
  src/styles/Theme/theme.ts
  src/types/types.ts
Labels: enhancement, v1.0, feature

#44 setting: cypress cloud 연동 및 PR cloud test , bundle size 체크
  .github/workflows/ci.yml
  README.md
  public/favicon.ico
Labels: setting, v1.0, 우선순위 높음

#46 setting: pr시 Lint 체크 CI 추가
  .github/workflows/ci.yml
Labels: enhancement, setting, v1.0, 우선순위 낮음

#48 setting: Test를 위한 netlify 배포 자동화 테스트
  .github/workflows/ci.yml
  package.json
  public/_redirects
Labels: enhancement, setting, v1.0, 우선순위 높음

#50 setting: og 세팅 & 배포 상태 badge 추가
  .github/workflows/ci.yml
  README.md
Labels: setting, v1.0, 우선순위 높음

#51 fix/reviewEdit : 리뷰 작성페이지 디자인 QA 반영
  src/api/client.ts
  src/components/blocks/Chips/index.style.tsx
  src/components/blocks/SelectBox/index.style.tsx
  src/components/blocks/SelectBox/index.tsx
  src/components/blocks/TextArea/index.style.tsx
  src/lib/service/service.ts
  src/styles/Theme/theme.ts
Labels: bug, v1.0, 우선순위 높음, fix

#55 feat/login: Redirect URI 변경
  src/App.tsx
  src/api/client.ts
  src/constants/login/index.ts
  src/lib/hooks/queries/login/index.ts
  src/lib/hooks/queries/login/useLogin.ts
  src/lib/hooks/useLogin.ts
  src/pages/login/index.tsx
  src/pages/login/kakaoSign.tsx
  src/pages/login/style.tsx
  src/types/login/login.d.ts
Labels: v1.0, feature, 우선순위 높음, fix

#57 feat/login: Minified React error #321 수정
  src/lib/hooks/queries/login/useLogin.ts
Labels: v1.0, 우선순위 높음, fix

#56 feat/loadingSpinner 로딩스피너 컴포넌트 추가 & 스켈레톤 테스트 제거
  cypress/e2e/2-typicode-test/typicode.cy.js
  cypress/fixtures/typicode/index.json
  package.json
  src/api/queryClient.ts
  src/components/atom/LoadingSpinner/LoadingHandler.tsx
  src/components/atom/LoadingSpinner/Spinner/FixedSpinner.tsx
  src/components/atom/LoadingSpinner/Spinner/Spinner.tsx
  src/components/atom/LoadingSpinner/Spinner/index.tsx
  src/components/atom/LoadingSpinner/index.tsx
  src/constants/motion/index.ts
  src/lib/util/ui/index.ts
  yarn.lock
Labels: enhancement, v1.0, feature, 우선순위 낮음
