Repository DDD-Community/jsonWeb-front, pull requests merged in 2022-11, with the labels that each got.

#16 [setting/init] CODEOWNERS, LICENSE 세팅
  .github/CODEOWNERS
  LICENSE
  README.md
Labels: setting, v1.0, 우선순위 낮음

#17 [setting/setHusky] update husky & pr template setting
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/.gitkeep
  .husky/pre-commit
  package.json
  src/components/blocks/block.tsx
Labels: documentation, setting, v1.0

#18 [test/rule] code review set test
  src/components/pages/pages.tsx
Labels: setting, v1.0

#19 디렉토리 구조 변경
  src/designsystem/atom/atom.tsx
  src/designsystem/blocks/block.tsx
  src/designsystem/pages/pages.tsx
  src/pages/components/cafeList/cafeList.tsx
  src/pages/components/detail/detail.tsx
  src/pages/components/login/login.tsx
  src/pages/components/myAccount/myAccount.tsx
Labels: setting, v1.0
