Repository DDD-Community/jsonWeb-front, pull requests merged in 2023-01, with the labels that each got.

#53 feat/reviewDeail : 리뷰 상세 페이지 구현
  cypress/e2e/3-review/detail.cy.js
  src/App.tsx
  src/assets/sample.png
  src/assets/svg/icon.tsx
  src/assets/svg/like.svg
  src/assets/svg/lockRate_small.svg
  src/assets/svg/star.svg
  src/assets/svg/starRate_small.svg
  src/components/atom/BoldTextSpan/index.tsx
  src/components/atom/Button/index.tsx
  src/components/atom/LikeBtn/index.tsx
  src/components/atom/atom.tsx
  src/components/atom/index.tsx
  src/components/blocks/Menu/index.tsx
  src/components/blocks/Menu/style.ts
  src/components/template/review/bottom/index.style.tsx
  src/components/template/review/bottom/index.tsx
  src/components/template/review/index.tsx
  src/components/template/review/item/index.style.tsx
  src/components/template/review/item/index.tsx
  src/components/template/review/top/index.style.tsx
  src/components/template/review/top/index.tsx
  src/constants/common/index.ts
  src/lib/util/index.ts
  src/lib/util/string.ts
  src/lib/util/util.ts
  src/pages/cafeList/index.tsx
  src/pages/review/detail/index.style.tsx
  src/pages/review/detail/index.tsx
  src/pages/search/index.tsx
  src/styles/Theme/theme.ts
  src/types/common/index.d.ts
  src/types/review/index.d.ts
  tsconfig.json
Labels: v1.0, feature, 우선순위 높음

#59 fix: setting: react-query-devtools 세팅, selectorbox 버그 수정, UserInfo header 컴포넌트 분리
  package.json
  src/App.tsx
  src/components/blocks/SelectBox/index.tsx
  src/components/blocks/UserInfo/index.style.tsx
  src/components/blocks/UserInfo/index.tsx
  src/components/template/review/item/index.style.tsx
  src/components/template/review/item/index.tsx
  src/components/template/review/top/index.style.tsx
  src/types/review/index.d.ts
  yarn.lock
Labels: bug, enhancement, v1.0, fix

#62 feat/certify: 인증 작성 UI 구현
  src/App.tsx
  src/components/atom/Button/index.tsx
  src/components/atom/LikeBtn/index.tsx
  src/components/blocks/Chips/index.style.tsx
  src/components/blocks/HashtagInput/index.tsx
  src/components/blocks/HashtagInput/style.tsx
  src/components/blocks/Header/style.ts
  src/components/blocks/SelectBox/index.style.tsx
  src/components/blocks/Star/index.tsx
  src/components/blocks/TextArea/index.style.tsx
  src/components/blocks/UserInfo/index.style.tsx
  src/components/template/review/bottom/index.style.tsx
  src/components/template/review/item/index.style.tsx
  src/components/template/review/top/index.style.tsx
  src/constants/index.ts
  src/pages/certify/edit/index.tsx
  src/pages/certify/edit/style.tsx
  src/pages/login/kakaoSign.tsx
  src/pages/login/style.tsx
  src/pages/myAccount/style.tsx
  src/styles/Theme/theme.ts
Labels: enhancement, v1.0

#66 [feat] react-query Suspense 추가
  package.json
  src/App.tsx
  src/api/queryClient.ts
  src/components/atom/BoldTextSpan/index.tsx
  src/components/atom/LoadingSpinner/Spinner/FixedSpinner.tsx
  src/components/atom/LoadingSpinner/index.tsx
  yarn.lock
Labels: enhancement, v1.0, 우선순위 높음

#67 [feat] data fetching 리뷰 상세 / 작성
  cypress/e2e/3-review/edit.cy.js
  src/App.tsx
  src/components/atom/LikeBtn/index.tsx
  src/components/atom/index.tsx
  src/components/blocks/Menu/index.tsx
  src/components/blocks/SelectBox/index.style.tsx
  src/components/blocks/SelectBox/index.tsx
  src/components/blocks/UserInfo/index.style.tsx
  src/components/blocks/UserInfo/index.tsx
  src/components/template/review/bottom/index.tsx
  src/components/template/review/item/index.style.tsx
  src/components/template/review/item/index.tsx
  src/components/template/review/top/index.tsx
  src/constants/common/index.ts
  src/lib/hooks/queries/review/index.ts
  src/lib/hooks/queries/review/useReviewCreateMutation.ts
  src/lib/hooks/queries/review/useReviewLikeMutation.ts
  src/lib/hooks/queries/themes/index.ts
  src/lib/hooks/queries/themes/useGetPopularEmotionById.ts
  src/lib/hooks/queries/themes/useGetThemeReviewListWithInfinite.ts
  src/lib/hooks/queries/themes/useGetThemesById.ts
  src/lib/hooks/queries/typicode/index.ts
  src/lib/hooks/queries/typicode/useGetTypiCodeById.ts
  src/lib/hooks/useIntersectionObserver/index.tsx
  src/lib/hooks/useIntersectionObserver/useIntersectionObserver.ts
  src/lib/hooks/useQueryString/index.tsx
  src/lib/hooks/useQueryString/useQueryString.ts
  src/pages/cafeList/index.tsx
  src/pages/review/edit/index.tsx
  src/pages/search/index.tsx
  src/pages/typiCode/index.tsx
  src/store/Typicode/TypicodeState.ts
  src/types/common/index.d.ts
  src/types/review/index.d.ts
  src/types/types.ts
  src/types/typicode/typicode.d.ts
Labels: v1.0, feature, 우선순위 높음

#70 feat: data fetching 리뷰 완료
  src/components/blocks/Chips/index.tsx
  src/components/blocks/UserInfo/index.tsx
  src/components/template/review/bottom/index.tsx
  src/components/template/review/item/index.tsx
  src/lib/hooks/queries/review/useReviewCreateMutation.ts
  src/lib/hooks/queries/review/useReviewLikeMutation.ts
  src/lib/util/string.ts
  src/pages/review/edit/index.tsx
  src/types/review/index.d.ts
Labels: enhancement, v1.0, feature, 우선순위 높음

#69 feat/certify: 인증 관련 페이지 UI 구현
  src/App.tsx
  src/assets/svg/icon.tsx
  src/assets/svg/more.svg
  src/components/atom/MoreBox/index.tsx
  src/components/atom/MoreBox/style.tsx
  src/components/blocks/Feed/index.tsx
  src/components/blocks/Feed/style.tsx
  src/components/blocks/MyHeader/index.tsx
  src/components/blocks/MyHeader/style.tsx
  src/components/blocks/UserInfo/index.style.tsx
  src/components/blocks/UserInfo/index.tsx
  src/components/template/boast/bottom/index.tsx
  src/components/template/boast/bottom/style.tsx
  src/components/template/boast/item/index.tsx
  src/components/template/boast/item/style.tsx
  src/constants/common/index.ts
  src/lib/data/mypageData.ts
  src/lib/data/navData.ts
  src/lib/hooks/queries/boast/index.ts
  src/lib/hooks/queries/boast/useBoastCreateMutation.ts
  src/lib/hooks/queries/boast/useBoastLikeMutation.ts
  src/lib/hooks/queries/boast/useGetAllBoastsWithInfinite.ts
  src/lib/hooks/queries/themes/useGetThemeBoastListWithInfinite.ts
  src/lib/hooks/queries/user/index.ts
  src/lib/hooks/queries/user/useLogin.ts
  src/pages/boast/edit/index.tsx
  src/pages/boast/edit/style.tsx
  src/pages/boast/list/index.tsx
  src/pages/boast/list/style.tsx
  src/pages/login/kakaoSign.tsx
  src/pages/login/style.tsx
  src/pages/myAccount/boast/index.tsx
  src/pages/myAccount/boast/style.tsx
  src/pages/myAccount/index.tsx
  src/pages/myAccount/like/index.tsx
  src/pages/myAccount/like/style.tsx
  src/pages/myAccount/review/index.tsx
  src/pages/myAccount/review/style.tsx
  src/pages/myAccount/style.tsx
  src/styles/Theme/theme.ts
  src/types/boast/index.d.ts
  src/types/review/index.d.ts
  src/types/types.ts
Labels: enhancement, v1.0, feature

#76 feat: ErrorBoundary, tracking 연동 등.. 추가
  .gitignore
  package.json
  public/index.html
  setupProxy.js
  src/App.tsx
  src/assets/sample.png
  src/assets/svg/default_img_1.svg
  src/assets/svg/default_img_2.svg
  src/assets/svg/icon.tsx
  src/components/blocks/UserInfo/index.tsx
  src/components/template/AppLayoutWrapper.tsx
  src/components/template/error/ErrorBoundary.tsx
  src/components/template/review/item/index.style.tsx
  src/components/template/review/item/index.tsx
  src/index.tsx
  src/lib/hooks/useDefaultProfile/index.tsx
  src/lib/hooks/useDefaultProfile/useDefaultProfile.ts
  src/lib/hooks/useRouteChangeTracker/index.tsx
  src/lib/hooks/useRouteChangeTracker/useRouteChangeTracker.ts
  yarn.lock
Labels: bug, enhancement, setting, v1.0, fix, 우선순위 낮음

#81 feat: Toast 추가
  src/App.tsx
  src/components/blocks/Toast/index.tsx
  src/components/blocks/UserInfo/index.tsx
  src/constants/motion/index.ts
  src/lib/hooks/queries/review/useReviewCreateMutation.ts
  src/lib/hooks/queries/themes/useGetThemeReviewListWithInfinite.ts
  src/pages/myAccount/boast/index.tsx
  src/pages/myAccount/review/index.tsx
  src/store/Toast/index.ts
  src/store/Toast/toastState.ts
  src/store/Toast/useToast.ts
  src/store/Typicode/TypicodeState.ts
  src/store/Typicode/index.ts
  src/styles/Theme/theme.ts
  src/types/types.ts
Labels: enhancement, v1.0, feature, 우선순위 높음, fix, style

#82 feat: 로딩 캐릭터 애니메이션 페이지 추가
  src/assets/svg/character.svg
  src/assets/svg/icon.tsx
  src/assets/svg/shadow.svg
  src/components/atom/LoadingSpinner/Spinner/CharacterSpinner.tsx
  src/components/atom/LoadingSpinner/Spinner/index.style.ts
  src/components/atom/LoadingSpinner/Spinner/index.tsx
  src/components/atom/LoadingSpinner/Spinner/svg/green-circle.svg
  src/components/atom/LoadingSpinner/Spinner/svg/green-star.svg
  src/components/atom/LoadingSpinner/Spinner/svg/index.tsx
  src/components/atom/LoadingSpinner/Spinner/svg/pink-circle.svg
  src/components/atom/LoadingSpinner/Spinner/svg/pink-star.svg
  src/components/atom/LoadingSpinner/Spinner/svg/yellow-circle.svg
  src/components/atom/LoadingSpinner/Spinner/svg/yellow-star.svg
  src/components/atom/LoadingSpinner/index.tsx
Labels: enhancement, v1.0, feature, 우선순위 높음, style

#83 feat/mypage: 마이페이지 및 인증게시판 API 연동
  src/assets/svg/icon.tsx
  src/assets/svg/setting.svg
  src/components/atom/LikeBtn/index.tsx
  src/components/atom/MoreBox/style.tsx
  src/components/blocks/Feed/index.tsx
  src/components/blocks/Feed/style.tsx
  src/components/blocks/Menu/style.ts
  src/components/blocks/MyHeader/index.tsx
  src/components/blocks/MyHeader/style.tsx
  src/components/blocks/UserInfo/index.style.tsx
  src/components/template/boast/item/index.tsx
  src/components/template/boast/item/style.tsx
  src/components/template/review/item/index.style.tsx
  src/lib/data/mypageData.ts
  src/lib/hooks/queries/user/index.ts
  src/lib/hooks/queries/user/useGetCurrentUser.ts
  src/lib/hooks/queries/user/useGetMyBoastWithInfinite.ts
  src/lib/hooks/queries/user/useGetMyLikeWithInfinite.ts
  src/lib/hooks/queries/user/useGetMyReviewWithInfinite.ts
  src/lib/hooks/queries/user/useLogin.ts
  src/pages/login/kakaoSign.tsx
  src/pages/myAccount/boast/index.tsx
  src/pages/myAccount/index.tsx
  src/pages/myAccount/like/index.tsx
  src/pages/myAccount/like/style.tsx
  src/pages/myAccount/review/index.tsx
  src/pages/myAccount/style.tsx
  src/styles/Theme/theme.ts
  src/types/boast/index.d.ts
  src/types/cafe/index.d.ts
  src/types/login/login.d.ts
  src/types/types.ts
  src/types/user/index.d.ts
Labels: v1.0, feature, 우선순위 높음

#87 feat: 신고하기 기능 및 페이지 완료
  src/App.tsx
  src/components/atom/Button/index.tsx
  src/components/atom/LoadingSpinner/Spinner/index.style.ts
  src/components/atom/RadioButton/index.style.tsx
  src/components/atom/RadioButton/index.tsx
  src/components/blocks/RadioGroup/index.style.tsx
  src/components/blocks/RadioGroup/index.tsx
  src/components/blocks/TextArea/index.style.tsx
  src/components/blocks/TextArea/index.tsx
  src/components/blocks/Toast/index.tsx
  src/components/blocks/UserInfo/index.tsx
  src/constants/index.ts
  src/lib/hooks/queries/member/.gitkeep
  src/lib/hooks/queries/report/index.ts
  src/lib/hooks/queries/report/useReportMutation.ts
  src/lib/hooks/queries/review/useReviewCreateMutation.ts
  src/pages/report/edit/index.style.tsx
  src/pages/report/edit/index.tsx
  src/pages/review/edit/index.style.tsx
  src/types/types.ts
Labels: v1.0, feature, 우선순위 높음

#88 setting: hotjar 연동
  package.json
  public/index.html
  src/index.tsx
  yarn.lock
Labels: setting, v1.0, 우선순위 낮음

#89 feat: ErrorBoundary 분기 처리 및 피그마 디자인 반영
  src/assets/svg/error.svg
  src/assets/svg/icon.tsx
  src/components/template/error/ErrorBoundary.tsx
  src/constants/index.ts
  src/lib/hooks/queries/themes/useGetThemesById.ts
  src/styles/Theme/theme.ts
Labels: enhancement, setting, v1.0, 우선순위 높음, fix, style

#91 setting: swc 추가 및 빌드 성능 개선
  craco.config.js
  package.json
  swcPlugin.js
  yarn.lock
Labels: enhancement, v1.0, fix, 우선순위 낮음

#93 [hotfix/feat] useQuery배포상태 에러 디버그 & 레이아웃 / 파비콘 적용
  netlify.toml
  package.json
  public/favicon.ico
  public/logo.png
  src/api/client.ts
  src/components/template/AppLayoutWrapper.tsx
  src/components/template/review/bottom/index.style.tsx
  src/constants/index.ts
  src/lib/hooks/queries/review/useReviewCreateMutation.ts
  src/lib/hooks/queries/review/useReviewLikeMutation.ts
  src/lib/hooks/queries/themes/useGetThemesById.ts
  src/pages/report/edit/index.style.tsx
  src/styles/Global.tsx
  yarn.lock
Labels: bug, setting, v1.0, 우선순위 높음, style, hotfix

#94 [hotifx] netlify proxy 설정 변경
  netlify.toml
  public/_redirects
Labels: hotfix
